derecha_de(llave,tortuga).
encima_de(coche,tortuga).
encima_de(bombilla,coche).
derecha_de(semaforo,llave).
encima_de(cafe,semaforo).
encima_de(lupa,cafe).
derecha_de(martillo,semaforo).
encima_de(balanza,martillo).
derecha_de(balanza,cafe).
