image: maven:3.5.0-jdk-8-alpine

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  JACOCO_AGENT:   "target/coverage/jacoco.exec"

stages:
  - build
  - test
  - qa
  - deploy

cache:
  paths:
    - .m2/repository
    - target/

build_job:
  stage: build
  script:
    - mvn --batch-mode compile -Dmaven.test.skip=true -Djacoco.skip=true

test_unit:
 stage: test
 script:
   - mvn test -P Unit

test_isolation:
 stage: test
 script:
   - mvn test -P Isolation
 except:
   - master
  
test_integration:
 stage: test
 script: 
   - mvn test -P Integration
 only:
   - master

sonar_publish_job:
  stage: qa
  before_script:
    - mvn -Djacoco.destFile=$JACOCO_AGENT clean org.jacoco:jacoco-maven-plugin:0.7.8:prepare-agent install
    - mvn -X -Djacoco.dataFile=$JACOCO_AGENT -Djacoco.outputDirectory=./jacoco_ut org.jacoco:jacoco-maven-plugin:report
  script:
    - mvn --batch-mode verify jxr:jxr pmd:pmd sonar:sonar -Dsonar.host.url=https://sonarqube.inf.uva.es -Dsonar.login=757a014b98b4ca240899c46bc5c0c5df15ea855b -Dsonar.analysis.mode=publish -Dsonar.issuesReport.console.enable=true -Dsonar.jacoco.reportPath=$JACOCO_AGENT -Dsonar.junit.reportPaths=target/surefire-reports
  coverage: /Total.*?([0-9]{1,3})%/
  only:
    - develop
    - master

sonar_preview_job:
  stage: qa
  before_script:
    - mvn -Djacoco.destFile=$JACOCO_AGENT clean org.jacoco:jacoco-maven-plugin:0.7.8:prepare-agent install
    - mvn -X -Djacoco.dataFile=$JACOCO_AGENT -Djacoco.outputDirectory=./jacoco_ut org.jacoco:jacoco-maven-plugin:report
  script:
    - mvn --batch-mode verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.0.1:sonar -Dsonar.host.url=https://sonarqube.inf.uva.es -Dsonar.login=757a014b98b4ca240899c46bc5c0c5df15ea855b -Dsonar.analysis.mode=preview -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME -Dsonar.gitlab.user_token=$GITLAB_USER_TOKEN -Dsonar.gitlab.url="https://gitlab.inf.uva.es" -Dsonar.issuesReport.console.enable=true -Dsonar.gitlab.only_issue_from_commit_line=true -Dsonar.gitlab.comment_no_issue=true -Dsonar.gitlab.disable_global_comment=true
  coverage: /Total.*?([0-9]{1,3})%/
  except:
    - develop
    - master

pages:
  stage: deploy
  script:
    - mvn install site
    - mkdir .public
    - cp -R target/site/* .public
    - rm -rf .public/xref
    - rm -rf .public/xref-test
    - mv .public public
  artifacts:
    paths:
      - public
    expire_in: 30 days

deploy:
  stage: deploy
  script:
    - mvn -$MAVEN_CLI_OPTS deploy
  only:
    - master
